### ISSUE TITLE
Running on MacOS?

### ISSUE THREAD

**Issue by mslmn** [TAAPArthur/amt#2]
Is it possible to get this running on macos? I've cloned the repo but running the `make install` command returns this error
```
/opt/homebrew/lib/python3.11/site-packages/setuptools/dist.py:561: UserWarning: The version specified ('.9') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
/opt/homebrew/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: could not create '/usr/share/amt': Operation not permitted
```

**Comment by TAAPArthur** [comment]
The first 2 lines are warnings that aren't blocking your install
The last line indicates you need to run the command as root to install globally. Ie `sudo make install`

**Comment by mslmn** [comment]
I get this error when I run it with sudo. 
```
python setup.py install "--root=/"
/bin/sh: python: command not found
make: *** [install] Error 127
```

If I try `sudo python3 setup.py install "--root=$(DESTDIR)/"` I get this error
```
zsh: command not found: DESTDIR
/opt/homebrew/lib/python3.11/site-packages/setuptools/dist.py:561: UserWarning: The version specified ('.9') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
/opt/homebrew/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: could not create '/usr/share/amt': Operation not permitted
```

**Comment by TAAPArthur** [comment]
Noted.
The first seems to due to not being able to find python. Do you not have a plain `python` binary/symlink?

The second issue is with the command. You don't want `$(DESTDIR)` here. Still think you'll hit the `Operation not permitted`. Looking into why.

In the mean time, you should be able to install with pip
`pip install --user $PATH_TO_GIT_REPO` where PATH_TO_GIT_REPO is where ever you checked the repo

**Comment by TAAPArthur** [comment]
Deleting 
```
 data_files=[("/usr/share/amt", ["scripts/auto_replace.sh", "scripts/merge_ts_files.sh"])],
```
in setup.py should avoid the permission denied error. Looking to see what the "new proper" way to do this is.

EDIT
Updated master

**Comment by mslmn** [comment]
Using pip install solves the issue. Thanks
